Repository meta-llama/llama, pull requests merged in 2023-09, with the labels that each got.

#490 Remove linkshim workaround from README
  README.md
Labels: CLA Signed

#727 use 'md5' instead of 'md5sum' if Applie Silicon
  download.sh
Labels: CLA Signed

#695 make download.sh executable
  download.sh
Labels: CLA Signed

#754 making a small change to avoid a confusion.
  llama/model.py
Labels: CLA Signed

#451 Update download.sh to not use hardcoded bash path for improved portability
  download.sh
Labels: CLA Signed, download-install

#765 Download FAQ
  Download.md
Labels: documentation, CLA Signed

#647 Return completion log probabilities
  llama/generation.py
Labels: bug, CLA Signed

#769 FAQ updates
  FAQ.md
Labels: CLA Signed

#775 Readme update
  README.md
Labels: CLA Signed

#779 add seed
  llama/generation.py
Labels: CLA Signed

#814 Update FAQ.md
  FAQ.md
Labels: CLA Signed

#813 Update MODEL_CARD.md
  MODEL_CARD.md
Labels: CLA Signed

#829 Update README.md
  README.md
Labels: CLA Signed

#822 Add "--continue" flag to wget for model binary in order to resume dl
  download.sh
Labels: CLA Signed
